#!/bin/bash
# QUICK REFERENCE - Commandes de Déploiement AUTO_StreamACMS
# À copier/coller directement dans le terminal

echo "════════════════════════════════════════════════════════════════════"
echo "  DÉPLOIEMENT AUTO_StreamACMS - GUIDE RAPIDE"
echo "════════════════════════════════════════════════════════════════════"

# ────────────────────────────────────────────────────────────────────
# ÉTAPE 1: SCP - Copier les fichiers depuis votre machine vers RPi
# ────────────────────────────────────────────────────────────────────
echo ""
echo "📤 ÉTAPE 1: COPIER LES FICHIERS (depuis votre machine Windows/Linux)"
echo "────────────────────────────────────────────────────────────────────"
echo ""
echo "Commande SCP:"
echo ""
echo "  scp -r \"E:\\Hanni\\ACMS\\AUTO_StreamACMS\" acms_tech@10.1.5.10:/home/acms_tech/"
echo ""
echo "Remarques:"
echo "  • Remplacer acms_tech par votre username RPi si différent"
echo "  • Remplacer 10.1.5.10 par l'IP réelle de votre RPi"
echo "  • Ajouter -i chemin/clé.pem si vous utilisez une clé SSH"
echo ""
echo "  Exemple avec clé SSH:"
echo "  scp -r -i ~/.ssh/id_rsa \"E:\\Hanni\\ACMS\\AUTO_StreamACMS\" acms_tech@10.1.5.10:/home/acms_tech/"
echo ""

# ────────────────────────────────────────────────────────────────────
# ÉTAPE 2: Configuration initiale sur RPi
# ────────────────────────────────────────────────────────────────────
echo ""
echo "🔧 ÉTAPE 2: CONFIGURATION INITIALE (sur RPi via SSH)"
echo "────────────────────────────────────────────────────────────────────"
echo ""
echo "Se connecter à RPi:"
echo "  ssh acms_tech@10.1.5.10"
echo ""
echo "Puis exécuter ces commandes:"
echo ""
echo "  cd /home/acms_tech/AUTO_StreamACMS"
echo "  chmod +x start_mawaqit_manager.sh"
echo "  mkdir -p logs schedules"
echo "  python3 -m pip install -r requirements.txt"
echo "  python3 test_paths.py"
echo ""
echo "Attendu après test_paths.py:"
echo "  RÉSULTAT: 6/6 tests réussis"
echo "  🎉 TOUS LES TESTS PASSENT - PRÊT À L'EXÉCUTION!"
echo ""

# ────────────────────────────────────────────────────────────────────
# ÉTAPE 3: Test manuel
# ────────────────────────────────────────────────────────────────────
echo ""
echo "🧪 ÉTAPE 3: TEST MANUEL (sur RPi)"
echo "────────────────────────────────────────────────────────────────────"
echo ""
echo "Lancer le script:"
echo "  ./start_mawaqit_manager.sh"
echo ""
echo "Dans un autre terminal, vérifier les logs:"
echo "  tail -f logs/mawaqit_stream.log"
echo ""
echo "Attendu:"
echo "  [INFO] MULTI-DEVICE MAWAQIT SYSTEM INITIALIZATION"
echo "  [INFO] DISCOVERING MAWAQIT BOXes ON VLAN 2 NETWORK"
echo "  [INFO] Connected to device..."
echo ""

# ────────────────────────────────────────────────────────────────────
# ÉTAPE 4: Ajouter à crontab
# ────────────────────────────────────────────────────────────────────
echo ""
echo "⏰ ÉTAPE 4: AJOUTER À CRONTAB (sur RPi)"
echo "────────────────────────────────────────────────────────────────────"
echo ""
echo "Ouvrir l'éditeur crontab:"
echo "  crontab -e"
echo ""
echo "Ajouter CETTE LIGNE à la fin du fichier:"
echo ""
echo "  */5 * * * * /home/acms_tech/AUTO_StreamACMS/start_mawaqit_manager.sh >> /home/acms_tech/AUTO_StreamACMS/logs/cron.log 2>&1"
echo ""
echo "Explication:"
echo "  */5 * * * *  = Relancer le processus toutes les 5 minutes"
echo "  >> logs/cron.log 2>&1  = Enregistrer les logs"
echo ""
echo "Alternatives:"
echo ""
echo "  Option 1 (Démarrage au boot uniquement):"
echo "  @reboot /home/acms_tech/AUTO_StreamACMS/start_mawaqit_manager.sh > /dev/null 2>&1 &"
echo ""
echo "  Option 2 (Démarrage + redémarrage maintenance à 2 AM):"
echo "  @reboot /home/acms_tech/AUTO_StreamACMS/start_mawaqit_manager.sh > /dev/null 2>&1 &"
echo "  0 2 * * * pkill -f mawaqit_stream_manager ; sleep 5 ; /home/acms_tech/AUTO_StreamACMS/start_mawaqit_manager.sh > /dev/null 2>&1 &"
echo ""

# ────────────────────────────────────────────────────────────────────
# ÉTAPE 5: Vérification
# ────────────────────────────────────────────────────────────────────
echo ""
echo "✅ ÉTAPE 5: VÉRIFICATION APRÈS DÉPLOIEMENT (sur RPi)"
echo "────────────────────────────────────────────────────────────────────"
echo ""
echo "Vérifier que crontab est bien configurée:"
echo "  crontab -l"
echo ""
echo "Vérifier que le processus tourne:"
echo "  ps aux | grep mawaqit_stream_manager"
echo ""
echo "Vérifier que le processus est dans la bonne arborescence:"
echo "  ls -la /home/acms_tech/AUTO_StreamACMS/"
echo ""
echo "Vérifier les logs en temps réel:"
echo "  tail -f /home/acms_tech/AUTO_StreamACMS/logs/mawaqit_stream.log"
echo ""
echo "Vérifier les logs de crontab:"
echo "  tail -f /home/acms_tech/AUTO_StreamACMS/logs/cron.log"
echo ""

# ────────────────────────────────────────────────────────────────────
# COMMANDES UTILES
# ────────────────────────────────────────────────────────────────────
echo ""
echo ""
echo "📋 COMMANDES UTILES POUR L'EXPLOITATION (sur RPi)"
echo "────────────────────────────────────────────────────────────────────"
echo ""
echo "Arrêter le processus (maintenance):"
echo "  pkill -TERM -f mawaqit_stream_manager"
echo ""
echo "Redémarrer le processus:"
echo "  pkill -f mawaqit_stream_manager && sleep 2 && /home/acms_tech/AUTO_StreamACMS/start_mawaqit_manager.sh"
echo ""
echo "Voir les erreurs:"
echo "  grep ERROR /home/acms_tech/AUTO_StreamACMS/logs/mawaqit_stream.log | tail -20"
echo ""
echo "Voir les prières détectées:"
echo "  grep PRAYER /home/acms_tech/AUTO_StreamACMS/logs/mawaqit_stream.log"
echo ""
echo "Voir la mémoire utilisée:"
echo "  ps aux | grep mawaqit_stream_manager | grep -v grep"
echo ""
echo "Monitorer en temps réel:"
echo "  top -p \$(pgrep -f mawaqit_stream_manager)"
echo ""

# ────────────────────────────────────────────────────────────────────
# RÉSUMÉ
# ────────────────────────────────────────────────────────────────────
echo ""
echo "════════════════════════════════════════════════════════════════════"
echo "  RÉSUMÉ - À FAIRE DANS L'ORDRE"
echo "════════════════════════════════════════════════════════════════════"
echo ""
echo "1. ✅ SCP: Copier les fichiers"
echo "   scp -r \"E:\\Hanni\\ACMS\\AUTO_StreamACMS\" acms_tech@10.1.5.10:/home/acms_tech/"
echo ""
echo "2. ✅ SSH: Configuration initiale"
echo "   ssh acms_tech@10.1.5.10"
echo "   cd /home/acms_tech/AUTO_StreamACMS && chmod +x start_mawaqit_manager.sh"
echo "   mkdir -p logs schedules && python3 -m pip install -r requirements.txt"
echo "   python3 test_paths.py"
echo ""
echo "3. ✅ TEST: Lancer manuellement"
echo "   ./start_mawaqit_manager.sh"
echo "   tail -f logs/mawaqit_stream.log"
echo ""
echo "4. ✅ CRON: Ajouter à crontab"
echo "   crontab -e"
echo "   */5 * * * * /home/acms_tech/AUTO_StreamACMS/start_mawaqit_manager.sh >> /home/acms_tech/AUTO_StreamACMS/logs/cron.log 2>&1"
echo ""
echo "5. ✅ VERIFY: Vérifier après reboot"
echo "   ps aux | grep mawaqit_stream_manager"
echo "   tail -f /home/acms_tech/AUTO_StreamACMS/logs/mawaqit_stream.log"
echo ""
echo "════════════════════════════════════════════════════════════════════"
echo "  🎉 DÉPLOIEMENT TERMINÉ!"
echo "════════════════════════════════════════════════════════════════════"
echo ""
